function [fitresult, gof] = createFit(w, y0)
%CREATEFIT(W,Y0)
%  Create a fit.
%
%  Data for 'myFit' fit:
%      X Input : w
%      Y Output: y0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jan-2021 23:42:45


%% Fit: 'myFit'.
[xData, yData] = prepareCurveData( w, y0 );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [1.07314059351766 5.02654824574367 -0.12072722585876 0.816603246961447 1.25663706143592 0.231369204144396];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% %figure( 'Name', 'myFit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y0 vs. w', 'myFit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'w', 'Interpreter', 'none' );
% ylabel( 'y0', 'Interpreter', 'none' );
% grid on


